### ISSUE TITLE
На сайте https://sh3tut.edu.yar.ru/  при  поиске "расписание" происходит переход сайта на версию для слабовидящих 

### ISSUE THREAD

**Issue by H4Rkotik** [SeregaTheDed/eda7k#2]
1) Заходим на сайт https://sh3tut.edu.yar.ru
![image](https://user-images.githubusercontent.com/113367737/203294456-83c55ae8-3ad3-4dab-9754-2afa5dd79c50.png)

2) В строке для поиска вбиваем слово "Расписание"
![image](https://user-images.githubusercontent.com/113367737/203294524-e229fad9-ab2f-4fc6-b8f5-619061ab2309.png)
Вроде бы всё окей)

3) Но если вбить слово "расписание" (то есть с маленькой буквы), то мы увидим это...
![image](https://user-images.githubusercontent.com/113367737/203294777-3ccaa097-f3e3-4de8-a8e0-5ea1e01a62e0.png)

4) Ожидаемое поведение: те же результаты, что при поиске "Расписание"

**Comment by SeregaTheDed** [comment]
Issue для пары. Больше не нужен.
