### ISSUE TITLE
Неправильная дата заказа

### ISSUE THREAD

**Issue by trlol** [SeregaTheDed/eda7k#6]
1. Захожу на сайт eda7k
2. Делаю заказ
![2022-12-20_00-27-03](https://user-images.githubusercontent.com/113424765/208527922-161434d6-d9d8-4bbe-b405-2507e77eaf28.png)
3. Заказ принят
![2022-12-20_00-27-37](https://user-images.githubusercontent.com/113424765/208528036-f360b81a-f762-4259-8698-ed5315c35db4.png)
4.Неправильная дата заказа в истории моих заказов
![2022-12-20_00-27-58](https://user-images.githubusercontent.com/113424765/208528131-d9fd8470-8fa5-4d12-817e-ad48d8184119.png)
Ожидание: Вывод заказа с сегодняшним числом

**Comment by SeregaTheDed** [comment]
Дата, на которую сделан заказ, устанавливается администратором. 
В вашем случае в админке
![image](https://user-images.githubusercontent.com/84785308/208606355-35c2d317-0fc6-4e9e-ba88-85f9c882a860.png)
Отсюда и получилась "Неправильная дата"
